# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('zipcode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('zipcode', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.CharField(default='User', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked', to='game.User'),
        ),
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='game.Shelter'),
        ),
        migrations.AddField(
            model_name='animal',
            name='passed_by',
            field=models.ManyToManyField(blank=True, related_name='passed', to='game.User'),
        ),
        migrations.AddField(
            model_name='animal',
            name='playdate',
            field=models.ManyToManyField(blank=True, related_name='scheduled_playdate', to='game.User'),
        ),
    ]
