# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
